name: Auth from Github Actions to AWS assuming an IAM role

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  access-secret:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: "arn:aws:iam::995692339962:role/Terraform1-Role"
        aws-region: "us-east1"

    - name: Run something on AWS
      run: aws s3 ls
